services:
  postgres:
    container_name: postgres_api
    image: postgres:16.3
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - apinest:/var/lib/postgresql/data
volumes:
  apinest:
